import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import { ThemeProvider } from "@/providers/theme-provider"
import { ModeToggle } from "@/components/theme-toogle";
import { CircleHelp } from "lucide-react";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
          <div className="grid grid-rows-[100px_1fr_20px] items-center justify-items-center min-h-screen p-8 gap-16 font-[family-name:var(--font-geist-sans)] bg-background text-foreground">
          <h1 className="row-start-1 text-4xl font-bold">Aujourd'hui, célébrons</h1>
          {children}
          <footer className="row-start-3 flex gap-2 w-full justify-end">
            <ModeToggle />
            <Link href="/about">
              <Button variant="outline" size="icon">
                <CircleHelp />
                <span className="sr-only">Help</span>
              </Button>
            </Link>
          </footer>
        </div>

        </ThemeProvider>
      </body>
    </html>
  )
}
